version: 2

sources:
  - name: airtable_sylvan_customer_management
    database: SYLVAN_INTERNAL_DATABASE
    schema: AIRTABLE_SYLVAN_CUSTOMER_MANAGEMENT_APPT2R0RWMCEQIPSR
    tables:
      - name: BASE_INVOICES
      - name: SUBSCRIPTIONS
